export const mockUser = {
  id: "user_1",
  name: "Alex Chen",
  email: "alex@example.com",
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "code", color: "#22c55e", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "sparkles", color: "#a855f7", isSystem: true },
  { id: "type_note", name: "Note", icon: "file-text", color: "#3b82f6", isSystem: true },
  { id: "type_command", name: "Command", icon: "terminal", color: "#f59e0b", isSystem: true },
  { id: "type_file", name: "File", icon: "file", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "image", color: "#ec4899", isSystem: true },
  { id: "type_url", name: "URL", icon: "link", color: "#06b6d4", isSystem: true },
];

export const mockCollections = [
  { id: "col_1", name: "React Patterns", description: "Reusable React component patterns", isFavorite: false, itemCount: 8 },
  { id: "col_2", name: "AI Prompts", description: "Curated prompts for development", isFavorite: false, itemCount: 3 },
  { id: "col_3", name: "DevOps Commands", description: "Docker, CI/CD, and deployment", isFavorite: false, itemCount: 5 },
];

export const mockItems = [
  {
    id: "item_1",
    title: "React useCallback Pattern",
    description: "Optimize callbacks in complex components.",
    content: `const memoized = useCallback(() => {\n  doSomething(a, b);\n}, [a, b]);`,
    contentType: "text",
    language: "tsx",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["react", "performance", "hooks"],
    isFavorite: true,
    isPinned: false,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-04-01T08:30:00Z",
  },
  {
    id: "item_2",
    title: "Explain Code Like Senior Dev",
    description: "Prompt for detailed code explanation.",
    content: `You are a senior software engineer. Explain the following code clearly and thoroughly...`,
    contentType: "text",
    language: null,
    typeId: "type_prompt",
    collectionId: "col_2",
    tags: ["ai", "code-review"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-18T14:00:00Z",
    updatedAt: "2026-03-28T11:00:00Z",
  },
  {
    id: "item_3",
    title: "Docker Compose Cheatsheet",
    description: "Common Docker Compose commands.",
    content: `docker compose up -d\ndocker compose down\ndocker compose logs -f`,
    contentType: "text",
    language: "bash",
    typeId: "type_command",
    collectionId: "col_3",
    tags: ["docker", "devops"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-15T09:00:00Z",
    updatedAt: "2026-03-29T16:00:00Z",
  },
  {
    id: "item_4",
    title: "API Error Handling Notes",
    description: "Notes on handling errors in REST APIs.",
    content: `Error handling strategies:\n- Use HTTP status codes correctly\n- Return consistent error shapes\n- Log with context`,
    contentType: "text",
    language: null,
    typeId: "type_note",
    collectionId: null,
    tags: ["api", "backend"],
    isFavorite: false,
    isPinned: true,
    createdAt: "2026-03-10T12:00:00Z",
    updatedAt: "2026-04-02T09:00:00Z",
  },
  {
    id: "item_5",
    title: "Tailwind Gradient Generator",
    description: "Snippet to generate CSS gradients with Tailwind.",
    content: `<div class="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500" />`,
    contentType: "text",
    language: "html",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["tailwind", "css"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-04-01T14:00:00Z",
  },
  {
    id: "item_6",
    title: "Git Release Interactive",
    description: "Interactive release workflow with git.",
    content: `git tag -a v1.0.0 -m "Release 1.0.0"\ngit push origin --tags`,
    contentType: "text",
    language: "bash",
    typeId: "type_command",
    collectionId: "col_3",
    tags: ["git"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-12T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "item_7",
    title: "Python FastAPI Template",
    description: "Starter template for FastAPI projects.",
    content: `from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\ndef read_root():\n    return {"Hello": "World"}`,
    contentType: "text",
    language: "python",
    typeId: "type_snippet",
    collectionId: null,
    tags: ["python", "fastapi", "api"],
    isFavorite: true,
    isPinned: false,
    createdAt: "2026-03-05T08:00:00Z",
    updatedAt: "2026-03-31T12:00:00Z",
  },
  {
    id: "item_8",
    title: "Generate PR Description",
    description: "AI prompt to write PR descriptions from diff.",
    content: `Review the following git diff and write a professional pull request description including summary, changes, and testing notes.`,
    contentType: "text",
    language: null,
    typeId: "type_prompt",
    collectionId: "col_2",
    tags: ["ai", "git", "pr"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-25T15:00:00Z",
    updatedAt: "2026-04-03T09:00:00Z",
  },
  {
    id: "item_9",
    title: "Zustand Store Pattern",
    description: "Simple Zustand state management setup.",
    content: `import { create } from 'zustand'\n\nconst useStore = create((set) => ({\n  count: 0,\n  increment: () => set((s) => ({ count: s.count + 1 })),\n}))`,
    contentType: "text",
    language: "tsx",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["react", "zustand", "state"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-03-28T13:00:00Z",
    updatedAt: "2026-04-04T10:00:00Z",
  },
];
